version: '3.8'

# services:
#   cocoa-api:
#     build:
#       context: .
#       dockerfile: Dockerfile.dev
#     container_name: cocoa-api
#     # depends_on: [cacao-postgres]
#     ports:
#       - 8080:8080
#     restart: always
#     env_file:
#       - .env

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aurora-cacao

  cacao-api:
    container_name: cacao-api
    build: .
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 9229:9229  # debugger port
    command: yarn start:docker
    env_file:
      - .env
    restart: always
    # environment:
    #   DATABASE_URL: postgresql://postgres:password@localhost:5432/aurora-cacao?schema=public
    #   PORT: 5000