export const APP_CONSTANTS = {
    RESPONSE: {
        ROOT: {
            SUCCESS: "You've reached the v1 API!",
            MISSING_DATA: 'Required Parameters are missing.',
        },
        BATCH: {
            MISSING_CODE: 'Missing Code.',
            UPDATE_SUCCESS: 'Values Updated Successfully!',
            FETCH_SUCCESS: 'Successfully fetched the batches!',
        },
        STORAGE: {
            INVALID_ID: 'Storage Phase Id is invalid!',
        },
        DRYING: {
            INVALID_ID: 'Drying Phase Id is invalid!',
        },
        SALES: {
            INVALID_ID: 'Sales Phase Id is invalid!',
        },
        PRODUCER: {
            MISSING_CODE: 'Missing Code.',
            UPDATE_SUCCESS: 'Producer Updated Successfully!',
            LINK_BATCH_EXISTS: 'Producer is already linked to this Batch!',
            FAILED_BATCH_CHANGE: 'Could not update Batches!',
            FETCH_SUCCESS: 'Successfully Fetched Producer Data!',
            SEARCH_SUCCESS: 'Successfully searched producers!',
        },
        ASSOCIATION: {
            FETCH_SUCCESS: 'Successfully Fetched Association Data!',
            NOT_FOUND: 'Association Does Not Exist!',
        },
        DEPARTMENT: {
            FETCH_SUCCESS: 'Successfully Fetched Department Data!',
            NOT_FOUND: 'Department Does Not Exist!',
        },
        FLIPS: {
            SAVE_SUCCESS: 'Flip added successfully.',
        },
    },
};

export const DB_CONSTANTS = {
    ROLES: ['buyer', 'association', 'project'] as const,
};

export const SYNC_ODK_FORM_IDS = [
    'Aurora-A-Productor',
    'Aurora-B-Colección',
    'Aurora-C-Fermentación',
    'Aurora-D-Secado',
    'Aurora-E-Almacenamiento',
    'Aurora-F-Ventas',
] as const;

export const AuroraAProductorFormEntries = [
    'SubmissionDate',
    'note1',
    'dateofsurvey',
    'starttime',
    'endtime',
    'enumerator',
    'association',
    'farmer_first_name',
    'farmer_last_name',
    'phone_number',
    'hhconsent',
    'grp_a_noconsent-noconsentwhy',
    'grp_a_noconsent-noconsentwhyoth',
    'a-resp_gender',
    'a-age',
    'a-department',
    'a-town',
    'a-village_name',
    'a-farm_name',
    'a-total_area',
    'a-cacao_area',
    'a-gpsloc-Latitude',
    'a-gpsloc-Longitude',
    'a-gpsloc-Altitude',
    'a-gpsloc-Accuracy',
    'a-lots',
    'a-lots_r_count',
    'a-protected',
    'a-protected_area',
    'a-water_sources',
    'a-water_sources_num',
    'a-test_code',
    'a-producer_code',
    'a-code_note',
    'thank_you_note',
    'duration',
    'end_of_survey',
    'gen_comment',
    'meta-instanceID',
    'meta-instanceName',
    'KEY',
    'SubmitterID',
    'SubmitterName',
    'AttachmentsPresent',
    'AttachmentsExpected',
    'Status',
    'ReviewState',
    'DeviceID',
    'Edits',
    'FormVersion',
] as const;

export const AuroraBColeccionFormEntries = [
    'SubmissionDate',
    'note1',
    'dateofsurvey',
    'starttime',
    'endtime',
    'enumerator',
    'farmer_first_name',
    'farmer_last_name',
    'phone_number',
    'hhconsent',
    'grp_a_noconsent-noconsentwhy',
    'grp_a_noconsent-noconsentwhyoth',
    'a-prod_code',
    'a-batch_code',
    'a-collection_date',
    'a-genetics',
    'a-batch_weight',
    'a-batch_quality',
    'a-batch_status',
    'a-batch_kg_price',
    'a-batch_total_price',
    'a-sales_receipt',
    'a-code_note',
    'thank_you_note',
    'gen_comment',
    'meta-instanceID',
    'meta-instanceName',
    'KEY',
    'SubmitterID',
    'SubmitterName',
    'AttachmentsPresent',
    'AttachmentsExpected',
    'Status',
    'ReviewState',
    'DeviceID',
    'Edits',
    'FormVersion',
] as const;

export const AuroraCFermentacionFormEntries = [
    'SubmissionDate',
    'seca_note1',
    'dateofsurvey',
    'starttime',
    'endtime',
    'a1_enumerator',
    'batch_code',
    'prod_code',
    'ferm_start_date',
    'genetics',
    'batch_weight',
    'drained',
    'hours_drained',
    'brix_degrees',
    'inital_temp',
    'ambient_temp',
    'humidity',
    'flips',
    'num_flips',
    'flips_r_count',
    'flips_r-flips_repeat_num',
    'flips_r-flip_time',
    'flips_r-flip_temp',
    'flips_r-flip_ambient',
    'flips_r-flip_humidity',
    'ferm_end_date',
    'ferm_days',
    'date_note',
    'code_note',
    'thank_you_note',
    'gen_comment',
    'meta-instanceID',
    'meta-instanceName',
    'KEY',
    'SubmitterID',
    'SubmitterName',
    'AttachmentsPresent',
    'AttachmentsExpected',
    'Status',
    'ReviewState',
    'DeviceID',
    'Edits',
    'FormVersion',
] as const;

export const AuroraDSecadoFormEntries = [
    'SubmissionDate',
    'seca_note1',
    'dateofsurvey',
    'starttime',
    'endtime',
    'enumerator',
    'batch_code',
    'dry_start_date',
    'dry_type',
    'dry_end_date',
    'dry_days',
    'date_note',
    'moisture_final',
    'thank_you_note',
    'gen_comment',
    'meta-instanceID',
    'meta-instanceName',
    'KEY',
    'SubmitterID',
    'SubmitterName',
    'AttachmentsPresent',
    'AttachmentsExpected',
    'Status',
    'ReviewState',
    'DeviceID',
    'Edits',
    'FormVersion',
] as const;

export const AuroraEAlmacenamientoFormEntries = [
    'SubmissionDate',
    'seca_note1',
    'dateofsurvey',
    'starttime',
    'endtime',
    'enumerator',
    'batch_code',
    'storage_date',
    'weight',
    'conversion',
    'ferm_percent',
    'grain_index',
    'sensorial',
    'sensorial_score',
    'thank_you_note',
    'gen_comment',
    'meta-instanceID',
    'meta-instanceName',
    'KEY',
    'SubmitterID',
    'SubmitterName',
    'AttachmentsPresent',
    'AttachmentsExpected',
    'Status',
    'ReviewState',
    'DeviceID',
    'Edits',
    'FormVersion',
] as const;

export const AuroraFVentasFormEntries = [
    'SubmissionDate',
    'note1',
    'dateofsurvey',
    'starttime',
    'endtime',
    'enumerator',
    'prod_code',
    'buyer',
    'tot_weight',
    'batch_lot',
    'lot_code',
    'nego_type',
    'nego_term',
    'dest_country',
    'currency',
    'val_kg',
    'batch_total_price',
    'total_note',
    'nego_date',
    'thank_you_note',
    'gen_comment',
    'meta-instanceID',
    'meta-instanceName',
    'KEY',
    'SubmitterID',
    'SubmitterName',
    'AttachmentsPresent',
    'AttachmentsExpected',
    'Status',
    'ReviewState',
    'DeviceID',
    'Edits',
    'FormVersion',
] as const;
